version: "3.7"

services:
  postgres:
    restart: always
    container_name: ${POSTGRES_REPOSITORY}_dev
    image: ${POSTGRES_GENEESPLAATS_NL_IMAGE}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    # networks:
      # - postgres-network
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  react:
    container_name: ${REACT_REPOSITORY}
    image: ${REACT_GENEESPLAATS_NL_IMAGE}:${REACT_GENEESPLAATS_NL_VERSION}
    restart: always
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    depends_on:
      - postgres
    expose:
      - "${REACT_APP_EXPOSE_PORT}"
    ports:
      - "${REACT_APP_EXPOSE_PORT}:${REACT_APP_EXPOSE_PORT}"
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
      - type: bind
        source: ./node_modules
        target: /usr/src/app/node_modules

    # networks:
      # - common-network
      # - react-network
    env_file:
      - ./.env
      - ./.docker-dev-env
      - ./.react_env

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  
# networks:
#   postgres-network:
#     driver: bridge
