version: "3.7"

services:
  postgres:
    restart: always
    container_name: ${POSTGRES_REPOSITORY}_prod
    image: ${POSTGRES_GENEESPLAATS_NL_IMAGE}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - postgres_backup_prod:/backups
    # networks:
      # - postgres-network
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  react:
    container_name: ${REACT_REPOSITORY}
    image: ${REACT_GENEESPLAATS_NL_IMAGE}:${REACT_GENEESPLAATS_NL_VERSION}
    restart: always
    build:
      context: ./
      dockerfile: ./docker/prod/Dockerfile
    depends_on:
      - postgres

    expose:
      - "${REACT_APP_EXPOSE_PORT}"
    ports:
      - "${REACT_APP_EXPOSE_PORT}:${REACT_APP_EXPOSE_PORT}"
    #networks:
    #  - react-network
    env_file:
      - ./.env
      - ./.docker-dev-env
      - ./.react_env
      
volumes:
  postgres_data_prod: {}
  postgres_backup_prod: {}

# networks:
#   postgres-network:
#     driver: bridge
