apiVersion: v1
kind: PersistentVolume
metadata:
  name: localhost-react-node-modules-volume
  labels:
    react-pv: node_modules
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/spikkieroot/projects/geneesplaats.nl/node_modules"
