apiVersion: v1
kind: PersistentVolume
metadata:
  name: localhost-react-src-volume
  labels:
    react-pv: src
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/spikkieroot/projects/geneesplaats.nl/src"
