apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: geneesplaats-nl-letsencrypt-production
  #name: geneesplaats-nl-letsencrypt-staging
  namespace: ingress-nginx
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: spikkie@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
      #name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx 
