apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: certificate-geneesplaat-nl
  namespace: default
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-staging
  commonName: geneesplaats.nl
  dnsNames:
  - geneesplaats.nl
