apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: geneesplaats-nl-letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: spikkie@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - http01:
       ingress:
         class: default
         #name: react-ingress 
