apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-env
  name: postgres-env
  namespace: nginx-ingress
data:
  DATABASE_URL: postgres://production_geneesplaats_nl_user:n7fseDI0vw42@postgres:5432/production_geneesplaats_nl
  DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: .geneesplaats.nl
  DJANGO_EXPOSE_PORT: "8001"
  DJANGO_GENEESPLAATS_NL_VERSION: latest
  DJANGO_SETTINGS_MODULE: config.settings.production
  ENVIRONMENT: production
  POSTGRES_DB: production_geneesplaats_nl
  POSTGRES_GENEESPLAATS_NL_VERSION: latest
  POSTGRES_PASSWORD: n7fseDI0vw42
  POSTGRES_USER: production_geneesplaats_nl_user
  PRODUCTION: "true"
  SECRET_KEY: ZT7i5QmzQTUUldzm1nU8XTrBz1lwCkyssMCt96q1ipmexs6I0E
