apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-my-proj-volume-claim
  namespace: nginx-ingress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


