language: go
sudo: required
services:
- docker
go:
- "1.14"
script:
- echo "Building ingress controller commit:${TRAVIS_COMMIT}"
- make container BUILD_IN_CONTAINER=0 DOCKER_BUILDKIT=0;
- echo "Helm smoke test"
- cd ${TRAVIS_BUILD_DIR} && wget -O helm.tar.gz https://get.helm.sh/helm-v3.0.3-linux-amd64.tar.gz &&
  tar xzfv helm.tar.gz -C ./ --strip-components=1 linux-amd64/helm
- ./helm template nginx-ingress deployments/helm-chart/
- ./helm template nginx-ingress deployments/helm-chart/ -f deployments/helm-chart/values-plus.yaml
- ./helm template nginx-ingress deployments/helm-chart/ -f deployments/helm-chart/values-icp.yaml
before_install:
- echo "PR Slug:${TRAVIS_PULL_REQUEST_SLUG}"
- if [[ "${TRAVIS_PULL_REQUEST_SLUG}" == "nginxinc/kubernetes-ingress" || "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
  wget https://github.com/fossas/fossa-cli/releases/download/v1.0.27/fossa-cli_1.0.27_linux_amd64.tar.gz && tar xzf fossa-cli_1.0.27_linux_amd64.tar.gz
  && ./fossa init
  && GO111MODULE=on FOSSA_API_KEY=${fossapush} ./fossa analyze -t kubernetes-ingress -b ${TRAVIS_BRANCH}; fi
- echo "Checking ingress controller for linting errors" && wget -O - -q ${golangci_lint} | sh -s v1.17.1
- export PATH="$PATH:./bin" && make lint
